### ISSUE TITLE
Syntax Errors

### ISSUE THREAD

**Issue by getcontrol** [fpaupier/pi-mask-detection#3]
For some reason I keep getting syntax errors when I run detect_mask.py on my Raspberry Pi 4 running Python3 , specifically around any code where there's colons in this format : 

`deployment: dict = operational_config["deployment"]`

(vs the previous format in the line before 
`mask_threshold = operational_config["models"]["mask_classifier"]["threshold"]`

as well as all the print statements where there's variables inside parentheses:      
`print(f"{len(faces)} Face(s) detected")  `

**Comment by fpaupier** [comment]
Hello,

 ["f-string" formatting](https://realpython.com/python-f-strings/)  used in such expressions:
>  `print(f"{len(faces)} Face(s) detected") `

was introduced in python 3.6. Do you use an older python version?
Note that for this repo, I recommend using python 3.7.

**Comment by getcontrol** [comment]
Thanks, I'm just generally having problems installing p3.7 on my pi it seems ! Keep getting problems with a. PIP and SSL errors and b. Installing PyYaml. Any chance you have a ethchable rpi image?

**Comment by getcontrol** [comment]
FWIW upgrading my RPI  Debian from stretch to buster then  installing Python3.7 from source did the trick for me (to get python3.7 running).
wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
tar xzvf Python-3.7.2.tgz
cd Python-3.7.2/
./configure
make -j4
sudo make install
